/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package myproject.tijada_oop;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import myproject.tijada_oop.SMS_DB.AMS;
/**
 *
 * @author jomsa
 */
public class Log_in extends javax.swing.JDialog {

    /**
     * Creates new form Log_in
     */
    public Log_in(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        initComponents();
        logInPnl.setBackground(new java.awt.Color(144, 238, 144));
        LogTransBttn.setBackground(new java.awt.Color(144, 238, 144));
        LogTransBttn.setForeground(Color.WHITE);
        seePassChckBx.setBackground(new java.awt.Color(144, 238, 144));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logInPnl = new javax.swing.JPanel();
        userNameLbl = new javax.swing.JLabel();
        createAccLbl = new javax.swing.JLabel();
        userNameTxtBx = new javax.swing.JTextField();
        passLbl = new javax.swing.JLabel();
        passTxtBx = new javax.swing.JPasswordField();
        seePassChckBx = new javax.swing.JCheckBox();
        alreadyLbl = new javax.swing.JLabel();
        LogTransBttn = new javax.swing.JButton();
        SignBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setForeground(new java.awt.Color(255, 153, 0));
        setResizable(false);

        userNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userNameLbl.setText("Username:");

        createAccLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        createAccLbl.setText("Create Account");

        userNameTxtBx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        passLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passLbl.setText("Password:");

        seePassChckBx.setText("See Password");
        seePassChckBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePassChckBxActionPerformed(evt);
            }
        });

        alreadyLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alreadyLbl.setText("Already have an account?");

        LogTransBttn.setBackground(new java.awt.Color(242, 242, 242));
        LogTransBttn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogTransBttn.setForeground(new java.awt.Color(51, 153, 255));
        LogTransBttn.setText("Log in");
        LogTransBttn.setBorder(null);
        LogTransBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogTransBttnActionPerformed(evt);
            }
        });

        SignBttn.setText("Sign in");
        SignBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInPnlLayout = new javax.swing.GroupLayout(logInPnl);
        logInPnl.setLayout(logInPnlLayout);
        logInPnlLayout.setHorizontalGroup(
            logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPnlLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passLbl)
                    .addComponent(userNameLbl))
                .addGap(18, 18, 18)
                .addGroup(logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(userNameTxtBx)
                    .addComponent(passTxtBx)
                    .addComponent(seePassChckBx, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPnlLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPnlLayout.createSequentialGroup()
                        .addComponent(createAccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPnlLayout.createSequentialGroup()
                        .addComponent(alreadyLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogTransBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        logInPnlLayout.setVerticalGroup(
            logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(createAccLbl)
                .addGap(35, 35, 35)
                .addGroup(logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLbl)
                    .addComponent(userNameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLbl)
                    .addComponent(passTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seePassChckBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(SignBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(logInPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alreadyLbl)
                    .addComponent(LogTransBttn))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logInPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logInPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void seePassChckBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePassChckBxActionPerformed
        // TODO add your handling code here:
        // Toggle password visibility
        if (seePassChckBx.isSelected()) {
            passTxtBx.setEchoChar((char) 0); // Show password
        } else {
            passTxtBx.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_seePassChckBxActionPerformed

    private void LogTransBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogTransBttnActionPerformed
        // TODO add your handling code here:
        // Toggle between Log In and Create Account modes
        if (isLogIn) {
            switchToCreateAccountMode();
        } else {
            switchToLogInMode();
        }
        clearInputFields();
        isLogIn = !isLogIn;
    }//GEN-LAST:event_LogTransBttnActionPerformed

    private void SignBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignBttnActionPerformed
        // TODO add your handling code here:
        // Validate input fields
        String username = userNameTxtBx.getText().replaceAll("\\s+", "").trim(); // Remove all whitespace
        String password = new String(passTxtBx.getPassword()).replaceAll("\\s+", "").trim(); // Remove all whitespace

        if (validateInputs(username, password)) {
            if (isLogIn) {
                handleLogIn(username, password);
            } else {
                handleSignUp(username, password);
            }
        }
    }//GEN-LAST:event_SignBttnActionPerformed

    private void switchToCreateAccountMode() {
        SwingUtilities.invokeLater(() -> {
            logInPnl.setBackground(new java.awt.Color(144, 238, 144)); // Light green for Create Account mode
            seePassChckBx.setBackground(new java.awt.Color(144, 238, 144));
            createAccLbl.setText("Create Account");
            LogTransBttn.setText("Log in");
            LogTransBttn.setBackground(new java.awt.Color(144, 238, 144));
            SignBttn.setText("Sign in");
            alreadyLbl.setText("Already have an account?");

            logInPnl.revalidate();
            logInPnl.repaint();
            seePassChckBx.revalidate();
            seePassChckBx.repaint();
            LogTransBttn.revalidate();
            LogTransBttn.repaint();
        });
    }

    private void switchToLogInMode() {
        SwingUtilities.invokeLater(() -> {
            logInPnl.setBackground(new java.awt.Color(173, 216, 230)); // Light blue for Log In mode
            seePassChckBx.setBackground(new java.awt.Color(173, 216, 230));
            createAccLbl.setText("Welcome Back!");
            LogTransBttn.setText("Sign In");
            LogTransBttn.setBackground(new java.awt.Color(173, 216, 230));
            SignBttn.setText("Log in");
            alreadyLbl.setText("Don't have an account?");

            logInPnl.revalidate();
            logInPnl.repaint();
            seePassChckBx.revalidate();
            seePassChckBx.repaint();
            LogTransBttn.revalidate();
            LogTransBttn.repaint();
        });
    }

    private void clearInputFields() {
        userNameTxtBx.setText("");
        passTxtBx.setText("");
    }

    private boolean validateInputs(String username, String password) {
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username cannot be empty.");
            return false;
        }
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password cannot be empty.");
            return false;
        }
        return true;
    }

    private void handleLogIn(String username, String password) {
        AMS log = new AMS();
        boolean success = log.LogIn(username, password); // Pass the actual values instead of text fields

        if (success) {
            openMenuForm();
        }
    }

    private void handleSignUp(String username, String password) {
        AMS sign = new AMS();
        boolean success = sign.SignUp(username, password); // Pass the actual values instead of text fields

        if (success) {
            openMenuForm();
        }
    }

    private void openMenuForm() {
        Menu menu = new Menu();
        this.dispose();
        menu.setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Log_in dialog = new Log_in(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }  
    boolean isLogIn = false;
    // Variables declaration - do not modify                     
    private javax.swing.JButton LogTransBttn;
    private javax.swing.JButton SignBttn;
    private javax.swing.JLabel alreadyLbl;
    private javax.swing.JLabel createAccLbl;
    private javax.swing.JPanel logInPnl;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passTxtBx;
    private javax.swing.JCheckBox seePassChckBx;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTxtBx;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
