/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myproject.tijada_oop;

/**
 *
 * @author jomsa
 */
public class Menu_Form extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Form
     */
    public Menu_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        filter = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        searchBttn = new javax.swing.JButton();
        studentFilter = new javax.swing.JRadioButton();
        profFilter = new javax.swing.JRadioButton();
        courseFilter = new javax.swing.JRadioButton();
        subjFilter = new javax.swing.JRadioButton();
        menBar = new javax.swing.JMenuBar();
        fileMen = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        createMen = new javax.swing.JMenu();
        mStudent = new javax.swing.JMenuItem();
        mProf = new javax.swing.JMenuItem();
        mCourse = new javax.swing.JMenuItem();
        mSubj = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 160, 0, 0));

        searchBttn.setText("Search");
        searchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBttnActionPerformed(evt);
            }
        });

        filter.add(studentFilter);
        studentFilter.setText("Student");
        studentFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentFilterActionPerformed(evt);
            }
        });

        filter.add(profFilter);
        profFilter.setText("Professor");

        filter.add(courseFilter);
        courseFilter.setText("Course");

        filter.add(subjFilter);
        subjFilter.setText("Subject");

        fileMen.setText("File");

        jMenuItem10.setText("Switch user");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        fileMen.add(jMenuItem10);

        jMenuItem5.setText("Log out");
        fileMen.add(jMenuItem5);

        menBar.add(fileMen);

        createMen.setText("Create");
        createMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMenActionPerformed(evt);
            }
        });

        mStudent.setText("Student");
        mStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mStudentActionPerformed(evt);
            }
        });
        createMen.add(mStudent);

        mProf.setText("Professor");
        mProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProfActionPerformed(evt);
            }
        });
        createMen.add(mProf);

        mCourse.setText("Course");
        mCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCourseActionPerformed(evt);
            }
        });
        createMen.add(mCourse);

        mSubj.setText("Subject");
        mSubj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSubjActionPerformed(evt);
            }
        });
        createMen.add(mSubj);

        menBar.add(createMen);

        setJMenuBar(menBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentFilter)
                        .addGap(18, 18, 18)
                        .addComponent(profFilter)
                        .addGap(18, 18, 18)
                        .addComponent(courseFilter)
                        .addGap(18, 18, 18)
                        .addComponent(subjFilter)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(searchBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentFilter)
                    .addComponent(profFilter)
                    .addComponent(subjFilter)
                    .addComponent(courseFilter))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void mProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProfActionPerformed
        // TODO add your handling code here:
        Professor prof = new Professor(this, true);
        prof.setVisible(true);
    }//GEN-LAST:event_mProfActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void searchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBttnActionPerformed
        // TODO add your handling code here:
        if(studentFilter.isSelected()){
            SearchStudent search = new SearchStudent(this, true);
            search.setVisible(true);
        }
        if(profFilter.isSelected()){
            SearchProf search = new SearchProf(this, true);
            search.setVisible(true);
        }
        if(courseFilter.isSelected()){
            SearchCourse search = new SearchCourse(this, true);
            search.setVisible(true);
        }
        if(subjFilter.isSelected()){
            SearchSubj search = new SearchSubj(this, true);
            search.setVisible(true);
        }
        
    }//GEN-LAST:event_searchBttnActionPerformed

    private void mStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mStudentActionPerformed
        // TODO add your handling code here:
        Student student = new Student(this, true); 
        student.setVisible(true);
        
    }//GEN-LAST:event_mStudentActionPerformed

    private void mCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCourseActionPerformed
        // TODO add your handling code here:
        Course course = new Course(this, true); 
        course.setVisible(true);
    }//GEN-LAST:event_mCourseActionPerformed

    private void mSubjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSubjActionPerformed
        // TODO add your handling code here:
        Subject subj = new Subject(this, true); 
        subj.setVisible(true);
    }//GEN-LAST:event_mSubjActionPerformed

    private void studentFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentFilterActionPerformed

    private void createMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createMenActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Form().setVisible(true);
            }
        });
    }
    private javax.swing.JRadioButton courseFilter;
    private javax.swing.JMenu createMen;
    private javax.swing.JMenu fileMen;
    private javax.swing.ButtonGroup filter;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JMenuItem mCourse;
    private javax.swing.JMenuItem mProf;
    private javax.swing.JMenuItem mStudent;
    private javax.swing.JMenuItem mSubj;
    private javax.swing.JMenuBar menBar;
    private javax.swing.JRadioButton profFilter;
    private javax.swing.JButton searchBttn;
    private javax.swing.JRadioButton studentFilter;
    private javax.swing.JRadioButton subjFilter;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
