/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package myproject.tijada_oop;

import myproject.tijada_oop.SMS_DB.Connect_DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jomsa
 */
public class SearchStudent extends javax.swing.JDialog {

    /**
     * Creates new form Search_Student
     */
    public SearchStudent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        Table_edit model = new Table_edit(
        new Object[][]{}, 
        new String[]{"Student ID", "Name", "Course", "Year"}
        );
        jTable2.setModel(model);
        
        loadAllStudents();// Loads all data immediately
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchFilter = new javax.swing.ButtonGroup();
        searchPnl = new javax.swing.JPanel();
        searchTxtBx = new javax.swing.JTextField();
        searchBttn = new javax.swing.JButton();
        trnsRb = new javax.swing.JRadioButton();
        rtrRb = new javax.swing.JRadioButton();
        newRb = new javax.swing.JRadioButton();
        oldRb = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        editBttn = new javax.swing.JButton();
        delBttn = new javax.swing.JButton();
        searchResTbl = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Course", "Year", "Section"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(320, 50, 0, 0));

        searchPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        searchTxtBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtBxActionPerformed(evt);
            }
        });

        searchBttn.setText("Search");
        searchBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBttnActionPerformed(evt);
            }
        });

        searchFilter.add(trnsRb);
        trnsRb.setText("Transferee");
        trnsRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trnsRbActionPerformed(evt);
            }
        });

        searchFilter.add(rtrRb);
        rtrRb.setText("Returnee");

        searchFilter.add(newRb);
        newRb.setText("New");
        newRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRbActionPerformed(evt);
            }
        });

        searchFilter.add(oldRb);
        oldRb.setText("Old");
        oldRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPnlLayout = new javax.swing.GroupLayout(searchPnl);
        searchPnl.setLayout(searchPnlLayout);
        searchPnlLayout.setHorizontalGroup(
            searchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(searchPnlLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(trnsRb, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtrRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(newRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(oldRb, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPnlLayout.setVerticalGroup(
            searchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPnlLayout.createSequentialGroup()
                .addGroup(searchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTxtBx)
                    .addComponent(searchBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(searchPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trnsRb)
                    .addComponent(rtrRb)
                    .addComponent(newRb)
                    .addComponent(oldRb))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        editBttn.setText("Edit");
        editBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBttnActionPerformed(evt);
            }
        });

        delBttn.setText("Delete");
        delBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBttnActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Course", "Year"
            }
        ));
        searchResTbl.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(editBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBttn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchResTbl)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchResTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBttn)
                    .addComponent(delBttn))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadAllStudents() {// Shows all the student whenever the search appears
        String sqlQuery = "SELECT sd.student_ID, sd.student_name, sr.program AS course, sr.yr_lvl "
                          + "FROM student_details sd "
                          + "INNER JOIN student_records sr ON sd.student_ID = sr.student_ID";

        try (Connection con = Connect_DB.connect();
             PreparedStatement pst = con.prepareStatement(sqlQuery);
             ResultSet rs = pst.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0); // Clear existing rows

            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getString("student_ID"),
                    rs.getString("student_name"),
                    rs.getString("course"),
                    rs.getInt("yr_lvl")
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading student data: " + e.getMessage());
        }
    }
    
    private void searchTxtBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtBxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtBxActionPerformed

    private void trnsRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trnsRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trnsRbActionPerformed

    private void newRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRbActionPerformed

    private void oldRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldRbActionPerformed

    private void searchBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBttnActionPerformed

        String enrolStat = getEnrollmentStatus();
        String keyword = searchTxtBx.getText().trim();

        String sqlQuery = buildSqlQuery(enrolStat, keyword);

        try (Connection con = Connect_DB.connect();
             PreparedStatement pst = con.prepareStatement(sqlQuery)) {

            setQueryParameters(pst, enrolStat, keyword);

            ResultSet rs = pst.executeQuery();
            populateTable(rs);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchBttnActionPerformed

    private void editBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBttnActionPerformed
        // TODO add your handling code here:
        EditStudent edit = new EditStudent(this, true);
        edit.setVisible(true);
    }//GEN-LAST:event_editBttnActionPerformed

    private void delBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBttnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int[] selectedRows = jTable2.getSelectedRows(); // Get selected rows

        if (selectedRows.length == 0) {
            showMessage("Please select at least one row to delete.");
            return;
        }

        if (!confirmDeletion()) {
            return;
        }

        try (Connection con = Connect_DB.connect()) {
            con.setAutoCommit(false); // Start transaction

            // Prepare delete statements
            try {
                for (int row : selectedRows) {
                    String studentID = (String) model.getValueAt(row, 0); // Get the Student ID from the table
                    deleteStudentRecords(con, studentID);
                }

                con.commit(); // Commit the transaction
                removeRowsFromTable(model, selectedRows);
                showMessage("Selected row(s) deleted successfully.");
            } catch (SQLException e) {
                con.rollback(); // Rollback transaction in case of error
                throw e;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            showMessage("Error deleting row(s): " + e.getMessage());
        }
    }//GEN-LAST:event_delBttnActionPerformed

    private String getEnrollmentStatus() {
        if (trnsRb.isSelected()) {
            return "Transferee";
        } else if (rtrRb.isSelected()) {
            return "Returnee";
        } else if (newRb.isSelected()) {
            return "New student";
        } else if (oldRb.isSelected()) {
            return "Old student";
        }
        return "";
    }
    
    private String buildSqlQuery(String enrolStat, String keyword) {
        StringBuilder sqlQuery = new StringBuilder("SELECT sd.student_ID, sd.student_name, sr.program AS course, sr.yr_lvl "
                                                  + "FROM student_details sd "
                                                  + "INNER JOIN student_records sr ON sd.student_ID = sr.student_ID ");

        boolean hasEnrollmentStatus = !enrolStat.isEmpty();
        boolean hasKeyword = !keyword.isEmpty();

        if (hasEnrollmentStatus) {
            sqlQuery.append("WHERE sr.enrol_stat = ?");
        }

        if (hasKeyword) {
            if (hasEnrollmentStatus) {
                sqlQuery.append(" AND ");
            } else {
                sqlQuery.append("WHERE ");
            }
            sqlQuery.append("(sd.student_name LIKE ? OR sd.student_ID LIKE ? OR sr.program LIKE ? OR sr.yr_lvl LIKE ?)");
        }

        return sqlQuery.toString();
    }
    
    private void setQueryParameters(PreparedStatement pst, String enrolStat, String keyword) throws SQLException {
        int parameterIndex = 1;

        if (!enrolStat.isEmpty()) {
            pst.setString(parameterIndex++, enrolStat);
        }

        if (!keyword.isEmpty()) {
            String likeKeyword = "%" + keyword + "%";
            pst.setString(parameterIndex++, likeKeyword);  // student_ID
            pst.setString(parameterIndex++, likeKeyword);  // student_name
            pst.setString(parameterIndex++, likeKeyword);  // program
            pst.setString(parameterIndex++, likeKeyword);  // yr_lvl
        }
    }
    
    private void populateTable(ResultSet rs) throws SQLException {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0); // Clear existing rows

        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getString("student_ID"),   // student_id
                rs.getString("student_name"), // student_name
                rs.getString("course"),       // program (alias as course)
                rs.getInt("yr_lvl")           // year
            });
        }
    }
    
    private boolean confirmDeletion() {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete the selected row(s)? This action cannot be undone.", 
            "Confirm Deletion", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        return confirm == javax.swing.JOptionPane.YES_OPTION;
    }
    
    private void deleteStudentRecords(Connection con, String studentID) throws SQLException {
        String[] deleteQueries = {
            "DELETE FROM student_details WHERE student_ID = ?",
            "DELETE FROM student_demo WHERE student_ID = ?",
            "DELETE FROM student_fam WHERE student_ID = ?",
            "DELETE FROM student_records WHERE student_ID = ?"
        };

        for (String query : deleteQueries) {
            try (PreparedStatement pst = con.prepareStatement(query)) {
                pst.setString(1, studentID);
                pst.executeUpdate();
            }
        }
    }
    
    private void removeRowsFromTable(DefaultTableModel model, int[] selectedRows) {
        // Remove rows from the table model (reverse order to avoid index issues)
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            model.removeRow(selectedRows[i]);
        }
    }
    
    private void showMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBttn;
    private javax.swing.JButton editBttn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton newRb;
    private javax.swing.JRadioButton oldRb;
    private javax.swing.JRadioButton rtrRb;
    private javax.swing.JButton searchBttn;
    private javax.swing.ButtonGroup searchFilter;
    private javax.swing.JPanel searchPnl;
    private javax.swing.JScrollPane searchResTbl;
    private javax.swing.JTextField searchTxtBx;
    private javax.swing.JRadioButton trnsRb;
    // End of variables declaration//GEN-END:variables
}
